services:
  db:
    image: postgres:15
    container_name: asteroids-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: asteroids
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asteroids-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/asteroids"
    command: ["pnpm", "run", "start:dev"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: asteroids-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=http://asteroids-backend:4000
    command: ["pnpm", "run", "dev"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
